x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: "1.0.0"
  publishedVersionMetadata:
    releaseNote: >-
      Initial release.
    releaseTypes:
      - Feature
    recommended: false

  images:
    '':
      properties:
        buyerAppFrontend.image.repo:
          type: REPO_WITH_REGISTRY
        buyerAppFrontend.image.tag:
          type: TAG
    biap_client_node_js:
      properties:
        biapClientNodeJS.image.repo:
          type: REPO_WITH_REGISTRY
        biapClientNodeJS.image.tag:
          type: TAG
    biap_igm_node_js:
      properties:
        biapIGMNodeJS.image.repo:
          type: REPO_WITH_REGISTRY
        biapIGMNodeJS.image.tag:
          type: TAG
    mongo:
      properties:
        mongo.image.repo:
          type: REPO_WITH_REGISTRY
        mongo.image.tag:
          type: TAG
    py_ondc_protocol:
      properties:
        pyOndcProtocol.image.repo:
          type: REPO_WITH_REGISTRY
        pyOndcProtocol.image.tag:
          type: TAG

  deployerServiceAccount:
      description: >
        Service account used by application deployer
      roles:
      - type: ClusterRole
        rulesType: CUSTOM
        rules:
        - apiGroups: ['rbac.authorization.k8s.io']
          resources:
          - clusterroles
          - clusterrolebindings
          verbs:
          - '*'
        - apiGroups: ['apiextensions.k8s.io']
          resources:
          - customresourcedefinitions
          verbs:
          - '*'
        - apiGroups: ['']
          resources:
          - persistentvolumes
          - persistentvolumeclaims
          verbs:
          - '*'
        - apiGroups: ['storage.k8s.io']
          resources:
          - storageclasses
          verbs:
          - '*'

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  appDomain:
    type: string
    title: AppDomain
    description: Ingress endpoint for buyer app
  biapClientNodeJS.replicas:
    type: integer
    title: BIAPCLIENTNODEJS REPLICAS
    description: No. of replicas to be deployed for biapClientNodeJS
  biapClientNodeJS.configMap.juspay_webhook_username:
    type: string
    title: JUSPAY Webhook Username
  biapClientNodeJS.secret.bap_private_key:
    type: string
    title: BAP Private Key
    description: BAP Private Key
  biapClientNodeJS.secret.bap_public_key:
    type: string
    title: BAP Public Key
    description: BAP Public Key
  biapIGMNodeJS.replicas:
    type: integer
    title: BIAPIGMNODEJS REPLICAS
    description: No. of replicas to be deployed for biap igm nodejs
  buyerAppFrontend.replicas:
    type: integer
    title: BUYER APP FRONTEND REPLICAS
    description: No. of replicas to be deployed for buyer app frontend
  buyerAppFrontend.configMap.react_app_firebase_auth_domain:
    type: string
    title: REACT APP FIREBASE AUTH DOMAIN
    description: React app firebase auth domain
  buyerAppFrontend.configMap.react_app_firebase_api_key:
    type: string
    title: REACT APP FIREBASE API KEY
    description: React app firebase api key
  mongo.replicas:
    type: integer
    title: No. of replicas to be deployed for mongodb
    description: No. of replicas to be deployed for mongodb
  mongo.storageSize:
    type: string
    title: MongoDB storageSize
    description: StorageSize for MongoDB volume
  pyOndcProtocol.replicas:
    type: integer
    title: No. of replicas to be deployed for pyOndcProtocol
    description: No. of replicas to be deployed for pyOndcProtocol
  pyOndcProtocol.secret.bap_private_key:
    type: string
    title: BAP Private Key
    description: BAP Private Key
  pyOndcProtocol.secret.bap_public_key:
    type: string
    title: BAP Public Key
    description: BAP Public Key

required:
- name
- namespace
- appDomain
- biapClientNodeJS.replicas
- biapClientNodeJS.configMap.juspay_webhook_username
- biapClientNodeJS.secret.bap_private_key
- biapClientNodeJS.secret.bap_public_key
- biapIGMNodeJS.replicas
- buyerAppFrontend.replicas
- buyerAppFrontend.configMap.react_app_firebase_auth_domain
- buyerAppFrontend.configMap.react_app_firebase_api_key
- mongo.replicas
- mongo.storageSize
- pyOndcProtocol.replicas
- pyOndcProtocol.secret.bap_private_key
- pyOndcProtocol.secret.bap_public_key