apiVersion: v1
data:
  JUSPAY_API_KEY: {{ .Values.biapClientNodeJS.secret.juspay_api_key | b64enc | quote }}
  BAP_PRIVATE_KEY: {{ .Values.biapClientNodeJS.secret.bap_private_key | b64enc | quote }}
  BAP_PUBLIC_KEY: {{ .Values.biapClientNodeJS.secret.bap_public_key | b64enc | quote }}
kind: Secret
metadata:
  name: biap-client-node-js-secret
  namespace: {{ .Release.Namespace }}
type: Opaque