apiVersion: v1
data:
  REACT_APP_BASE_URL: https://{{ .Values.appDomain }}/
  REACT_APP_FIREBASE_AUTH_DOMAIN: {{ .Values.buyerAppFrontend.configMap.react_app_firebase_auth_domain }}
  REACT_APP_GOOGLE_API_KEY: ""
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-frontend-cm
  namespace: {{ .Release.Namespace }}