apiVersion: v1
data:
  REACT_APP_FIREBASE_API_KEY: {{ .Values.buyerAppFrontend.secret.react_app_firebase_api_key | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Values.appName }}-frontend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque