apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: mongodb-svc
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongo.image.repo }}:{{ .Values.mongo.image.tag }}
          ports:
            - containerPort: {{ .Values.mongo.port }}
          volumeMounts:
            - name: data
              mountPath: /data/db
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 1Gi
          livenessProbe:
            tcpSocket:
              port: {{ .Values.mongo.port }}
            initialDelaySeconds: 60  
            periodSeconds: 300
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.mongo.storageSize }}
        storageClassName: {{ .Values.appName }}-ssdstorageclass
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
