apiVersion: v1
data:
  BAP_PRIVATE_KEY: {{ .Values.pyOndcProtocol.secret.bap_private_key | b64enc | quote }}
  BAP_PUBLIC_KEY: {{ .Values.pyOndcProtocol.secret.bap_public_key | b64enc | quote }}
kind: Secret
metadata:
  name: py-ondc-protocol-secret
  namespace: {{ .Release.Namespace }}
type: Opaque