apiVersion: v1
data:
  ENV: "prod"  
  MONGO_DATABASE_HOST: "mongodb-svc.{{ .Release.Namespace }}.svc.cluster.local"
  BAP_URL: "https://{{ .Values.appName }}/protocol/v1"
  CLIENT_WEBHOOK_ENDPOINT: "https://{{ .Values.appName }}/clientApis/response"
  REGISTRY_BASE_URL: "https://agrih.registry.ondc.org/ondc"
  VERIFICATION_ENABLE: "true"
  BAP_UNIQUE_KEY_ID: "814"
  BAP_ID: "{{ .Values.appName }}"
kind: ConfigMap
metadata:
  name: py-ondc-protocol-cm
  namespace: {{ .Release.Namespace }}