appName: buyer-app
appDomain: buyer-app.ondcsutr.com

biapClientNodeJS:
  replicas: 1
  image: 
    repo: gcr.io/chaincodeconsulting-llp-public/buyer_app/biap_client_node_js
    tag: 1.0.0
  configMap:
    juspay_webhook_username: ONDC
    juspay_base_url: ""
    firebase_admin_service_account: ""
    domain: ""
    city: ""
    country: IND
    bap_unique_key_id: 814
    port: 3000
    node_dev: dev
    env_type: testing
    juspay_merchant_id: ONDC
  secret:
    juspay_api_key: ""
    bap_private_key: ""
    bap_public_key: ""

biapIGMNodeJS:
  replicas: 1
  image: 
    repo: gcr.io/chaincodeconsulting-llp-public/buyer_app/biap_igm_node_js
    tag: 1.0.0
  port: 6969
  configMap:
    domain: nic2004:52110
    country: IND

buyerAppFrontend:
  replicas: 1
  image:
    repo: gcr.io/chaincodeconsulting-llp-public/buyer_app/buyer_app_frontend
    tag: 1.0.0
  configMap:
    react_app_firebase_auth_domain: ""
  secret:
    react_app_firebase_api_key: ""

mongo:
  replicas: 1
  port: 27017
  image:
    repo: gcr.io/chaincodeconsulting-llp-public/buyer_app/mongo
    tag: 1.0.0
  storageSize: 5Gi

pyOndcProtocol:
  replicas: 1
  port: 5555
  image:
    repo: gcr.io/chaincodeconsulting-llp-public/buyer_app/py-ondc-protocol
    tag: 1.0.0
  secret:
    bap_private_key: ""
    bap_public_key: ""